### ISSUE TITLE
v.1.2.3版本登陆米游社没有反应

### ISSUE THREAD

**Issue by MrMoRenJ** [qyinter/yuanshenlink#1]
v1.2.2版本在10月13日尝试登陆米游社时，使用手机号和验证码登陆，提示需要同意许可协议。
10月13日更新为v.1.2.3版本，发现执行第一步登陆时界面没有反应，无法输入信息；点击第二步“点击获取并复制链接“，提示先登陆米游社

平台：安卓
机型：小米12pro
版本：MIUI13.0.30

**Comment by MrMoRenJ** [comment]
> v1.2.2版本在10月13日尝试登陆米游社时，使用手机号和验证码登陆，提示需要同意许可协议。 10月13日更新为v.1.2.3版本，发现执行第一步登陆时界面没有反应，无法输入信息；点击第二步“点击获取并复制链接“，提示先登陆米游社

**Comment by qyinter** [comment]
你看看，我git上面版本是多少。你下载我git上面的版本试试

**Comment by qyinter** [comment]
1.2.2版本，那个网页是可以滑动的，你滑动到下面就有，那个同意协议了，1.2.3别人改的，我不知道改了啥。

**Comment by MrMoRenJ** [comment]
老版本安装包不小心被删了，期待后续的更新
