### ISSUE TITLE
今天依旧没办法获取到数据

### ISSUE THREAD

**Issue by NOWorEVER** [qyinter/yuanshenlink#10]

**Comment by iamqwert** [comment]
我这边也是，link用的两天前新版

**Comment by unshineYL** [comment]
博主说是获取不到stoken了，这个项目基本黄了，但是说除非扫码登录。
希望博主弄个扫码登录的

**Comment by k-ying** [comment]
> 博主说是获取不到stoken了，这个项目基本黄了，但是说除非扫码登录。 希望博主弄个扫码登录的

如果能扫描登录也不错，可以手机上装平板来扫之类的

**Comment by qyinter** [comment]
风险太高,不整了.

**Comment by masm611** [comment]
米哈游改接口了
考虑使用云原神抽卡记录导出工具：
https://github.com/masm611/YunYuanshen-Wish-Export

使用方法录屏：
https://www.bilibili.com/video/BV15b42187Rw

这个项目不需要扫码，通过云原神网页版获取记录地址。
都用云原神了，所以没有风险。

**Comment by unshineYL** [comment]
我是b服的账号，5开头的，之前yuanshenlink上可以选择uid，这个只能官服，以后只能PC抓包了

**Comment by qyinter** [comment]
> 米哈游改接口了
> 
> 考虑使用云原神抽卡记录导出工具：
> 
> https://github.com/masm611/YunYuanshen-Wish-Export
> 
> 
> 
> 使用方法录屏：
> 
> https://www.bilibili.com/video/BV15b42187Rw
> 
> 
> 
> 这个项目不需要扫码，通过云原神网页版获取记录地址。
> 
> 都用云原神了，所以没有风险。

看了看排队有点烦。其他还好

**Comment by masm611** [comment]
> > 米哈游改接口了
> > 
> > 考虑使用云原神抽卡记录导出工具：
> > 
> > https://github.com/masm611/YunYuanshen-Wish-Export
> > 
> > 
> > 
> > 使用方法录屏：
> > 
> > https://www.bilibili.com/video/BV15b42187Rw
> > 
> > 
> > 
> > 这个项目不需要扫码，通过云原神网页版获取记录地址。
> > 
> > 都用云原神了，所以没有风险。
> 
> 看了看排队有点烦。其他还好

其实没放假的话就不会排队。放假期间大清早7点也不会排队，9点前队伍都很短

**Comment by qyinter** [comment]
好了,已经更新了,后续有一件可以说

**Comment by NOWorEVER** [comment]
> 好了,已经更新了,后续有一件可以说

爱了

**Comment by TRIM5829** [comment]
> 风险太高,不整了.

既然之前都有网页登陆米游社了，再出一个扫码登录的版本，还能有什么风险呢
