### ISSUE TITLE
登陆成功了还是显示请先登陆米游社

### ISSUE THREAD

**Issue by MASPV** [qyinter/yuanshenlink#11]

**Comment by nonstophello** [comment]
我也是，登录上了，复制就提示，解决了嘛

**Comment by masm611** [comment]
米哈游改接口了
考虑使用云原神抽卡记录导出工具：
https://github.com/masm611/YunYuanshen-Wish-Export

使用方法录屏：
https://www.bilibili.com/video/BV15b42187Rw

这个项目不需要扫码，通过云原神网页版获取记录地址。

**Comment by qyinter** [comment]
好的谢谢你,已经替换为云原神版本了

**Comment by nonstophello** [comment]
> 米哈游改接口了 考虑使用云原神抽卡记录导出工具： https://github.com/masm611/YunYuanshen-Wish-Export
> 
> 使用方法录屏： https://www.bilibili.com/video/BV15b42187Rw
> 
> 这个项目不需要扫码，通过云原神网页版获取记录地址。

可惜我是b服的，b的云游戏不行吧
