### ISSUE TITLE
登录成功后仍提示请先登录米又舍

### ISSUE THREAD

**Issue by WeiCY** [qyinter/yuanshenlink#12]
<img width="440" alt="image" src="https://github.com/qyinter/yuanshenlink/assets/17762251/23f24b06-957a-4c89-ae19-c396b41c3cb2">

**Comment by qyinter** [comment]
你就不能下个最新的？

**Comment by WeiCY** [comment]
刚刚下载的最新的1.3.0&nbsp;


阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月8日(星期三) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qyinter/yuanshenlink] 登录成功后仍提示请先登录米又舍 (Issue #12)














 
你就不能下个最新的？

**Comment by qyinter** [comment]
?你下错了吧

**Comment by WeiCY** [comment]
不好意思。是我的问题 模拟器没能覆盖安装 &nbsp; 我卸载后重新安装就好了




阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qyinter/yuanshenlink"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qyinter/yuanshenlink] 登录成功后仍提示请先登录米又舍 (Issue #12)





 
你就不能下个最新的？
