### ISSUE TITLE
话说回来，使用了masm611@github.com费尽千辛万苦发现的方法，不给原项目链接，还打别的公众号的广告是是不是过了点？

### ISSUE THREAD

**Issue by masm611** [qyinter/yuanshenlink#13]
而且还关闭之前的Issue（而且实际还没有完全解决）

**Comment by TRIM5829** [comment]
> 而且还关闭之前的Issue（而且实际还没有完全解决）

而且获取抽卡链接后不能继续进行游戏操作了，希望下次更新时解决哦

**Comment by qyinter** [comment]
> 而且还关闭了之前的问题（而且实际上还没有完全解决）

叫你麻痹呢，真以为就你们知道这个方法呢。
同行那个不知道？圈子都这么大，没有点b数？懒得喷。
还优越起来了，取展柜api 那个不也是你爹先做出来的？
你那点破玩意 ，也好意思在这叫，不知道叫的什么东西。
