### ISSUE TITLE
国际服无法登入米游社

### ISSUE THREAD

**Issue by chansheunglong** [qyinter/yuanshenlink#2]
国际服/港澳台服用的是海外版的米游社，无法登入账户
会新增对国际版的支持吗？

**Comment by qyinter** [comment]
那个api，国际服应该是没有，不知道有没有大佬发现，我这边测试了好多次，一直显示致命错误。不知道为啥。

**Comment by butterflywaltz** [comment]
国际服应该也是有的？

https://webapi.account.mihoyo.com
国际服可能是
webapi-os.account.mihoyo.com
webapi-os.account.hoyolab.com
webapi-os.account.hoyoverse.com

以下参考了https://github.com/thesadru/genshinstats/blob/master/genshinstats/genshinstats.py

https://api-takumi.mihoyo.com
国际服是
api-os-takumi.mihoyo.com

https://hk4e-api.mihoyo.com/
国际服是
hk4e-api-os.hoyoverse.com/

希望有帮助，我新手机是个安卓

**Comment by qyinter** [comment]
试过了，没用都是致命错误

**Comment by Undefined0326** [comment]
同国际服登不了，手机号显示格式错误账号显示密码错误

**Comment by Xiao-0417** [comment]
测试了国际服的对应API，是能够成功获取到部分数据的，包括stoken，ltoken和游戏内的用户信息。致命错误出现应该是在genauthkey这个API的请求头DS上，在研究了https://github.com/thesadru/genshinstats/blob/master/genshinstats/genshinstats.py
这个项目后，可以发现国服和国际服在计算DS数据时使用的salt是不同的，因此在使用国际服的genauthkeyAPI时会返回Invalid request

**Comment by qyinter** [comment]
我早测试了，从泄露开始的所有salt，
不对的ds直接就是Invalid request
对的会显示致命错误。
我试了1天放弃了，你们可以继续试试，
加油。
