### ISSUE TITLE
可以做出书签版吗？

### ISSUE THREAD

**Issue by Abigorangee** [qyinter/yuanshenlink#3]
看到有一个平台做出了书签版本的祈愿链接读取，手动登录mys通行证，然后点开存着如下内容的浏览器书签：
javascript:(function(){const s=document.createElement('script');s.src='https://ys.jdsha.com/static_js/ys.js';document.body.append(s)})();
就可以导出祈愿记录了

但是这个记录只有在他们自己的小程序可以解析，其他平台都会显示authkey error之类的错误，不知道是否是有加密。

**Comment by Abigorangee** [comment]
感觉书签版还是比较方便的，ios平台也可以使用。您的电脑端EXE程序和安卓端的APP都可以制作出通用的祈愿解析链接，不知道这个书签版本的解析能否实现

不论如何，感谢您的设计与付出！

**Comment by qyinter** [comment]
理论上来讲可以实现，但是我没啥兴趣搞了。

**Comment by Abigorangee** [comment]
> 理论上来讲可以实现，但是我没啥兴趣搞了。

uh，了解了，谢谢大佬！

**Comment by qyinter** [comment]
苹果等我不懒的 时候再说吧

**Comment by ZYFDroid** [comment]
从脚本内容看，这个js会把cookie和token上传到第三方平台，建议谨慎使用

**Comment by wangshantao** [comment]
这个竟然不是公司的项目嘛

**Comment by qyinter** [comment]
不是公司的，书签版，我做了个自用的。因为不放心的人很多

**Comment by AlexTeamX** [comment]
iOS版获取抽卡链接，通过TestFlight安装：https://testflight.apple.com/join/hWT0e1sT
