### ISSUE TITLE
v1.2.5版本，无论用短信还是密码登录都获取不了

### ISSUE THREAD

**Issue by k-ying** [qyinter/yuanshenlink#9]
RT，也尝试了账密登录，获取链接的时候还是提示请先登录米游社
![Screenshot_20240427_153029](https://github.com/qyinter/yuanshenlink/assets/61576272/18e519cf-4067-436b-a73e-2c1f8d777d82)

**Comment by mouxinxin** [comment]
死在了genauthkey，返回message：登录失效，请重新登录

**Comment by uyingchuan** [comment]
一样用不了，1.2.2和1.2.5都无法获取

**Comment by mouxinxin** [comment]
![image](https://github.com/qyinter/yuanshenlink/assets/87917688/cdbdf162-4709-45ce-a8d7-67a0c009ca8c)

**Comment by mouxinxin** [comment]
更改salt后返回值不是登录失效，应该可以排除salt变更

**Comment by qyinter** [comment]
api获取不到stoken，除非客户端扫码登录，用game_token换stoken，这个项目基本黄了。
